export const MEASUREMENT_TYPE = {
  MEASUREMENT: "MEASUREMENT",
  TEMPERATURE_MEASUREMENT: "TEMPERATURE_MEASUREMENT",
  FOG_LEVEL_MEASUREMENT: "FOG_LEVEL_MEASUREMENT",
  WIND_MEASUREMENT: "WIND_MEASUREMENT",
  AIR_QUALITY_MEASUREMENT: "AIR_QUALITY_MEASUREMENT",
  ATMOSPHERIC_PRESSURE_MEASUREMENT: "ATMOSPHERIC_PRESSURE_MEASUREMENT",
  CLOUD_COVERT_MEASUREMENT: "CLOUD_COVERT_MEASUREMENT",
} as const;
